
install: true

before_script:
  - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
  - 'unzip awscli-bundle.zip'
  - './awscli-bundle/install -b ~/bin/aws'
  - 'export PATH=~/bin:$PATH'

script: ./validate_templates.sh

deploy:
  provider: s3
  bucket: "cloudformation-snippets"
  acl: authenticated_read
  skip_cleanup: true
  local_dir: templates



